### ISSUE TITLE
Crash in live preview mode

### ISSUE THREAD

**Issue by windily-cloud** [elias-sundqvist/obsidian-react-components#26]
I guess it is caused by this obsidian update
env：v0.13.19，win11/mac, new vault without other plugins

recreate: 
![image](https://user-images.githubusercontent.com/30640638/150466916-ced4e1df-ed2c-45eb-9382-30e41c45a722.png)
1. create a new md file
2. create a component like this
````
---
defines-react-components: true
---

```jsx:component:Test
return <h1>test</h1>
```

```jsx:Test
````
3. when i input ```jsx:Test , then crash
![image](https://user-images.githubusercontent.com/30640638/150467334-c0c00d07-d23c-4e41-a433-067783c7cca2.png)

If i use legacy mode, it works fine.

**Comment by elias-sundqvist** [comment]
Yeah, it seems like one of the recent obsidian updates made my solution for live preview code blocks stop working.

I have almost managed to fix it, but I haven't found a way to hide the original code block that works in the new version. So you always see both the code and the resulting react component.

I'll spend some more time looking for a solution this weekend.

**Comment by elias-sundqvist** [comment]
I've released a new version now (0.1.6) which should resolve the issue.

**Comment by windily-cloud** [comment]
Thank you very much for taking the time to fix this problem。
But I still have a questions, I don't know if it is as you expected. 

![test](https://user-images.githubusercontent.com/30640638/150666532-c0af66d1-acad-4a1f-a61e-3ceb40eddce1.gif)

live preview mode:
As shown in the gif, I put two identical components in one file, and when I press the down button, I can't get to the next line. As the same time, when I press up key from bottom to top, I can move the cursor freely, but the first component is not rendered.

**Comment by elias-sundqvist** [comment]
That looks like a bug. Thanks for reporting it.
